from .status import StatusList, StatusDict
from .queueserver import add_status


GLOBAL_DETECTORS = StatusDict()
GLOBAL_DETECTOR_DESCRIPTIONS = StatusDict()
GLOBAL_ACTIVE_DETECTORS = StatusList()
GLOBAL_PLOT_DETECTORS = StatusList()

add_status("ACTIVE_DETECTORS", GLOBAL_ACTIVE_DETECTORS)
add_status("DETECTOR_DESCRIPTIONS", GLOBAL_DETECTOR_DESCRIPTIONS)
add_status("DETECTORS", GLOBAL_DETECTORS)
add_status("PLOT_DETECTORS", GLOBAL_PLOT_DETECTORS)

GLOBAL_MOTORS = StatusDict()
GLOBAL_MOTOR_DESCRIPTIONS = StatusDict()

add_status("MOTORS", GLOBAL_MOTORS)
add_status("MOTOR_DESCRIPTIONS", GLOBAL_MOTOR_DESCRIPTIONS)

GLOBAL_SETTINGS = StatusDict()
add_status("SETTINGS", GLOBAL_SETTINGS)
