# Template devices.toml file
# Copy this file and modify according to your beamline's needs

# Example Motor Configuration
[sample_x]
_target = "nbs_bl.devices.motors.DeadbandEpicsMotor"
name = "Sample X"
prefix = "MOTOR:X:"
_group = "motors"
tolerance = 0.1

# Example Detector Configuration
[main_detector]
_target = "nbs_bl.devices.detectors.ophScalar"
name = "Main Detector"
prefix = "DET:MAIN:"
_group = "detectors"
_role = "primary"
description = "Main measurement detector"
rescale = 1.0

# Example Shutter Configuration
[photon_shutter]
_target = "nbs_bl.devices.shutters.EPS_Shutter"
name = "Photon Shutter"
prefix = "PS:"
_group = "shutters"
_role = "default_shutter"
openval = 1
closeval = 0

# Example Sample Holder Configuration
[sample_holder]
_target = "nbs_bl.devices.sampleholders.Manipulator4AxBase"
name = "Sample Manipulator"
prefix = "MANIP:"
attachment_point = [0, 0, 0]
beam_direction = [0, -1, 0]
rotation_ax = 2
_group = "manipulators"
_role = "primary_sampleholder"

# Example Deferred Loading Device
[special_detector]
_target = "some.package.SpecialDetector"
name = "Special Detector"
prefix = "SPECIAL:"
_defer_loading = true
description = "Special detector that is loaded only when needed"
_group = "detectors"